/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package global

class Library {
    boolean someLibraryMethod() {
        true
    }
    def foo() {
        println 'test groovy library'
    }
}
